<h1 style="color: #FF4933;text-align: center;font-size: 3em;">application de neo4j pour trouver l'emplacement le plus proche de mon localisation actuelle</h1>

 <h1 style="color: green;text-align: center;font-size: 2em;">1   localisation actuelle  <h1>

In [19]:
import geocoder

def get_precise_location():
    try:
        # Utiliser le service de géolocalisation de OpenStreetMap
        location = geocoder.osm('me')
        
        # Extraire les informations de localisation
        address = location.address
        latlng = location.latlng  # Latitude et longitude

        # Retourner les informations de localisation
        return {
            "address": address,
            "latitude": latlng[0],
            "longitude": latlng[1]
        }
    
    except Exception as e:
        print(f"Une erreur s'est produite: {e}")
        return None

# Exemple d'utilisation
location = get_precise_location()
if location:
    print(f"Adresse: {location['address']}")
    print(f"Latitude: {location['latitude']}")
    print(f"Longitude: {location['longitude']}")

Adresse: Crna Gora / Црна Гора
Latitude: 42.9868853
Longitude: 19.5180992

 <h1 style="color: green;text-align: center;font-size: 2em;">2     recuperrer les hotels <h1>

In [2]:
import osmnx as ox
# Coordonnées géographiques de Fès
fes_location = (34.0331, -5.0003)
# Télécharger les données OpenStreetMap pour la région de Fès
graph = ox.graph_from_point(fes_location, dist=10000, network_type='all')
# Extraire les nœuds correspondant aux hôtels
hotels = ox.geometries.geometries_from_place('Fès', tags={'tourism': 'hotel'})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16992\1700126786.py:7: UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  hotels = ox.geometries.geometries_from_place('Fès', tags={'tourism': 'hotel'})

In [3]:
import pandas as pd
# Créer une liste vide pour stocker les données
data = []
# Parcourir les lignes du dataframe hotels
for index, row in hotels.iterrows():
    #  Extraire les coordonnées du point central du polygone
    centroid = row['geometry'].centroid
    latitude = centroid.y
    longitude = centroid.x
    # Ajouter les données de chaque ligne à la liste
    data.append({'name': row['name'], 'latitude': latitude, 'longitude': longitude,'type':'hotel'})
# Créer le DataFrame à partir de la liste de données
hotel = pd.DataFrame(data)
hotel=hotel.dropna()
# Afficher le DataFrame
hotel

                                          name   latitude  longitude   type
0                                 Palais Jamai  34.069217  -4.974194  hotel
1                                 Hôtel Mounia  34.036309  -4.996784  hotel
2                              Hôtel Volubilis  34.035278  -5.003424  hotel
3                                  Hotel Royal  34.043073  -5.001128  hotel
4                                Hotel Cascade  34.061797  -4.983736  hotel
..                                         ...        ...        ...    ...
93  Fes Marriott Hotel Jnan Palace فندق ماريوت  34.031789  -5.002804  hotel
94                      Hotel Perla فندق بيرلا  34.043789  -5.005235  hotel
95                             Villa Agapanthe  34.001826  -4.951168  hotel
97                               Les Merinides  34.069562  -4.981777  hotel
98                                Palais Amani  34.067471  -4.972057  hotel

[85 rows x 4 columns]

 <h1 style="color: green;text-align: center;font-size: 2em;">3 recuperrer des hospitals  <h1>

In [4]:
import osmnx as ox
# Coordonnées géographiques de Fès
fes_location = (34.0331, -5.0003)
# Télécharger les données OpenStreetMap pour la région de Fès
graph = ox.graph_from_point(fes_location, dist=10000, network_type='all')
# Extraire les nœuds correspondant aux hôtels
hospitals= ox.geometries.geometries_from_place('Fès', tags={'amenity': 'hospital'})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16992\3019711606.py:7: UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  hospitals= ox.geometries.geometries_from_place('Fès', tags={'amenity': 'hospital'})

In [10]:
import pandas as pd
# Créer une liste vide pour stocker les données
data = []
# Parcourir les lignes du dataframe hotels
for index, row in hospitals.iterrows():
    #  Extraire les coordonnées du point central du polygone
    centroid = row['geometry'].centroid
    latitude = centroid.y
    longitude = centroid.x
    # Ajouter les données de chaque ligne à la liste
    data.append({'name': row['name'], 'latitude': latitude, 'longitude': longitude,'type':'hospital'})
# Créer le DataFrame à partir de la liste de données
hospital = pd.DataFrame(data)
hospital=hospital.dropna()
# Afficher le DataFrame
hospital

,name,latitude,longitude,type
0,Centre hospitalier universitaire Hassan II,34.003677,-4.963796,hospital
1,Cabinet de Rheumatologie,34.036985,-5.001934,hospital
2,University hospital Hassan II,34.004460,-4.962440,hospital
3,Clinique RAIS,34.033517,-5.006211,hospital
4,Croissant rouge marocain,34.038193,-5.000622,hospital
5,Hôpital Omar Drissi,34.057517,-4.981428,hospital
6,مستشفى ابن البتطار,34.042576,-4.984736,hospital
7,الكوثر,34.014323,-4.999702,hospital
8,Hopital Ibn Alkhatib,34.063656,-4.990157,hospital
9,مستشفى الغساني,34.044666,-4.985025,hospital
10,Centre de santé adarissa المركز الصحي الادارسة,34.017392,-5.013606,hospital
11,dispenssaire ain zliten,34.064106,-4.980957,hospital
12,croissant rouge el batha الهلال الاحمر,34.059814,-4.982088,hospital
13,docteur Générale,34.060298,-4.981619,hospital
14,Hopital Ibn Khaldoun,34.063329,-4.990591,hospital

 <h1 style="color: green;text-align: center;font-size: 2em;">4   recuperrer des ecoles  <h1>

In [11]:
import osmnx as ox
# Coordonnées géographiques de Fès
fes_location = (34.0331, -5.0003)
# Télécharger les données OpenStreetMap pour la région de Fès
graph = ox.graph_from_point(fes_location, dist=10000, network_type='all')
# Extraire les nœuds correspondant aux hôtels
schools= ox.geometries.geometries_from_place('Fès', tags={'amenity': 'school'})

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12900\2801214153.py:7: UserWarning: The `geometries` module and `geometries_from_X` functions have been renamed the `features` module and `features_from_X` functions. Use these instead. The `geometries` module and function names are deprecated and will be removed in a future release.
  schools= ox.geometries.geometries_from_place('Fès', tags={'amenity': 'school'})

In [12]:
import pandas as pd
# Créer une liste vide pour stocker les données
data = []
# Parcourir les lignes du dataframe hotels
for index, row in schools.iterrows():
    #  Extraire les coordonnées du point central du polygone
    centroid = row['geometry'].centroid
    latitude = centroid.y
    longitude = centroid.x
    # Ajouter les données de chaque ligne à la liste
    data.append({'name': row['name'], 'latitude': latitude, 'longitude': longitude,'type':'school'})
# Créer le DataFrame à partir de la liste de données
school = pd.DataFrame(data)
school=school.dropna()
# Afficher le DataFrame
school

                                        name   latitude  longitude    type
0                    GSU Jean de La Fontaine  34.034586  -5.001701  school
1    Ecole Nationale des Sciences Appliquées  33.989725  -5.002275  school
2             Ecole Supérieure de tehnologie  33.989136  -5.002260  school
3                      Ecole primaire Slaoui  34.037733  -4.995414  school
4                            مدرسة ابن خلدون  34.062912  -4.993391  school
..                                       ...        ...        ...     ...
308                   Groupe Scolaire HILILI  34.004933  -5.016171  school
309               Groupe Scolaire Al Kalam 2  34.022053  -4.994087  school
310                          Lycée Ibn Arabi  34.026278  -5.043657  school
311                     Abdellah Chefchaouni  34.011397  -4.978226  school
316                     Abdellah Chefchaouni  34.011569  -4.978188  school

[302 rows x 4 columns]

 <h1 style="color: green;text-align: center;font-size: 2em;">5 compiner les dataset dans data <h1>

In [13]:
# Concaténer les DataFrames en un seul
frames = [hospital,school,hotel]
data = pd.concat(frames, ignore_index=True)
data

,name,latitude,longitude,type
0,Centre hospitalier universitaire Hassan II,34.003677,-4.963796,hospital
1,Cabinet de Rheumatologie,34.036985,-5.001934,hospital
2,University hospital Hassan II,34.004460,-4.962440,hospital
3,Clinique RAIS,34.033517,-5.006211,hospital
4,Croissant rouge marocain,34.038193,-5.000622,hospital
...,...,...,...,...
397,Fes Marriott Hotel Jnan Palace فندق ماريوت,34.031789,-5.002804,hotel
398,Hotel Perla فندق بيرلا,34.043789,-5.005235,hotel
399,Villa Agapanthe,34.001826,-4.951168,hotel
400,Les Merinides,34.069562,-4.981777,hotel
401,Palais Amani,34.067471,-4.972057,hotel

# aussi la localisation actuelle

In [23]:
import pandas as pd

# Supposons que vous ayez un nouveau lieu à ajouter
new_place = {'name': 'Position actuel','latitude': 34.0331,'longitude': -5.0003,"type":"localisation"}
# Convertir le dictionnaire en DataFrame
new_row = pd.DataFrame([new_place])
# Ajouter la nouvelle ligne au DataFrame existant
data = data.append(new_row, ignore_index=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12900\1813548786.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(new_row, ignore_index=True)

# transfermer en fichier csv pour la visualisation dans power bi

In [16]:
data.to_csv("data.csv")

 <h1 style="color: green;text-align: center;font-size: 2em;">6   stocker data dans neo4j  <h1>

In [20]:
from neo4j import GraphDatabase

# Définir les informations de connexion
uri = "bolt://localhost:7687"
username = "neo4j"
password = "halima.123"

# Définir la fonction pour créer un nœud pour chaque lieu
def create_place_node(tx, place):
    tx.run("CREATE (p:Place {name: $name, latitude: $latitude, longitude: $longitude, type: $type})", name=place['name'], latitude=place['latitude'], longitude=place['longitude'], type=place['type'])

# Connexion à la base de données Neo4j
driver = GraphDatabase.driver(uri, auth=(username, password))

# Création d'un nœud pour chaque lieu
with driver.session() as session:
    for index, row in data.iterrows():
        session.write_transaction(create_place_node, {'name': row['name'], 'latitude': row['latitude'], 'longitude': row['longitude'], 'type': row['type']})

# Fermeture de la connexion Neo4j
driver.close()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_12900\290655271.py:18: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(create_place_node, {'name': row['name'], 'latitude': row['latitude'], 'longitude': row['longitude'], 'type': row['type']})

 <h1 style="color: #FF4933;text-align: center;font-size: 3em;"> requests cypher dans neo4j <h1/>

<h1 style="color:#FF33F6;text-align: center;">1  Récupérer tous les lieux de type hotel :<h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; height: 100vh;">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            #Récupérer tous les lieux de type hôtel :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 10px; text-align: left; white-space: pre-wrap; word-wrap: break-word;">
            MATCH (p:Place {type: 'hotel'})<br>
            RETURN p
        </div>
    </div>
</div>

<h1 style="color:#FF33F6;text-align: center;">2  Récupérer la position actuel:<h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; height: 100vh;">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            #Récupérer le lieu nommé 'Position actuel' :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 10px; text-align: left; white-space: pre-wrap; word-wrap: break-word;">
            MATCH (p:Place {name: 'Position actuel'})<br>
            RETURN p
        </div>
    </div>
</div>

<h1 style="color:#FF33F6;text-align: center;">3 calculer et ajouter la relation distance entre Poistion actuel et tous les neaud <h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; ">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            Script Cypher pour calculer les distances entre "Position actuel" et tous les autres lieux :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 5px; text-align: left; ; word-wrap: break-word;">
            // Récupérer les coordonnées de "Position actuel"<br>
            MATCH (p:Place {name: 'Position actuel'})<br>
            WITH point({latitude: p.latitude, longitude: p.longitude}) AS currentPosition<br>
            <br>
            // Calculer la distance entre "Position actuel" et tous les autres nœuds et créer des relations avec la distance comme propriété<br>
            MATCH (n:Place)<br>
            WHERE n &lt;&gt; p<br>
            WITH p, n, currentPosition, point({latitude: n.latitude, longitude: n.longitude}) AS nodePosition<br>
            CREATE (p)-[r:DISTANCE_TO]->(n)<br>
            SET r.distance = point.distance(currentPosition, nodePosition)
        </div>
    </div>
</div>

<h1 style="color:#FF33F6;text-align: center;">3 Nombre de  Relation dans le dataset <h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh;">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            Script Cypher pour compter le nombre de relations :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 10px; text-align: left; white-space: pre-wrap; word-wrap: break-word;">
            // Compter le nombre de relations créées<br>
            MATCH ()-[r:DISTANCE_TO]->()<br>
            RETURN COUNT(r) AS numberOfRelationships
        </div>
    </div>
</div>

<h1 style="color:#FF33F6;text-align: center;">4 Récupérer le type d'hôtel le plus proche de la position actuelle:<h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh;">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            Script Cypher pour récupérer le type d'hôtel le plus proche de la position actuelle :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 10px; text-align: left; white-space: pre-wrap; word-wrap: break-word;">
            // Récupérer le type d'hôtel le plus proche de la position actuelle avec toutes ses données<br>
            MATCH (p:Place {name: 'Position actuel'})-[r:DISTANCE_TO]->(n:Place {type: 'hotel'})<br>
            WITH n, r.distance AS distance<br>
            ORDER BY distance ASC<br>
            LIMIT 1<br>
            RETURN n AS hotelData, distance
        </div>
    </div>
</div>

<h1 style="color:#FF33F6;text-align: center;">5 Récupérer le type de schole le plus proche de la position actuelle:<h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh;">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            Script Cypher pour récupérer le type d'ecole le plus proche de la position actuelle avec toutes ses données :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 10px; text-align: left; white-space: pre-wrap; word-wrap: break-word;">
            // Récupérer le type d'ecole le plus proche de la position actuelle avec toutes ses données<br>
            MATCH (p:Place {name: 'Position actuel'})-[r:DISTANCE_TO]->(n:Place {type: 'school'})<br>
            WITH n, r.distance AS distance<br>
            ORDER BY distance ASC<br>
            LIMIT 1<br>
            RETURN n AS hotelData, distance
        </div>
    </div>
</div>

<h1 style="color:#FF33F6;text-align: center;">5 Récupérer le type de hospital le plus proche de la position actuelle:<h1/>

<div style="font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; display: flex; justify-content: center; align-items: center; min-height: 100vh;">
    <div style="background-color: #ffffff; border: 1px solid #d3d3d3; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); padding: 20px; text-align: center;">
        <div style="color: #333333; font-size: 20px; font-weight: bold; margin-bottom: 10px;">
            Script Cypher pour récupérer le type d'hôpital le plus proche de la position actuelle avec toutes ses données :
        </div>
        <div style="background-color: #f9f9f9; border-left: 4px solid #0073e6; color: #333333; font-family: monospace; padding: 10px; text-align: left; white-space: pre-wrap; word-wrap: break-word;">
            // Récupérer le type d'hôpital le plus proche de la position actuelle avec toutes ses données<br>
            MATCH (p:Place {name: 'Position actuel'})-[r:DISTANCE_TO]->(n:Place {type: 'hospital'})<br>
            WITH n, r.distance AS distance<br>
            ORDER BY distance ASC<br>
            LIMIT 1<br>
            RETURN n AS hospitalData, distance
        </div>
    </div>
</div>

 <h1 style="color: #FF4933;text-align: center;font-size: 3em;"> tracer et afficher le chemin par folium et l'api graphhopper <h1/>

In [29]:
import requests
import folium
import polyline
# Points de départ et d'arrivée
start_point = (34.0188698, -4.9870592)
end_point = (34.0320889 , -4.9999488)
# Clé API GraphHopper
api_key = "6675d14f-1060-46a5-9202-257fb62d348e"
# URL de l'API GraphHopper
url = f"https://graphhopper.com/api/1/route?point={start_point[0]},{start_point[1]}&point={end_point[0]},{end_point[1]}&vehicle=car&key={api_key}"
# Demander l'itinéraire à l'API GraphHopper
response = requests.get(url)
data = response.json()
# Obtenir les points encodés à partir de la réponse de l'API
encoded_points = data['paths'][0]['points']
# Décoder les points encodés pour obtenir les coordonnées du chemin
decoded_points = polyline.decode(encoded_points)
# Coordonnées géographiques de Fès
fes_location = [34.0181, -5.0078]
# Création de la carte centrée sur Fès
fes_map = folium.Map(location=fes_location, zoom_start=12)
folium.Marker(location=[34.0320889 ,-4.9999488],popup="Hotel le plus proche",icon=folium.Icon(color="green", icon="info-sign")).add_to(fes_map)
folium.Marker(location=[34.0188698, -4.9870592],popup="Votre position actuelle",icon=folium.Icon(color="red", icon="info-sign")).add_to(fes_map)
# Tracer le chemin sur la carte
folium.PolyLine(locations=decoded_points,color='blue',weight=5,opacity=0.7).add_to(fes_map)
# Afficher la carte
fes_map.save("chemin_drive.html")